name: dribbbledanimation
description: A new Flutter project.

dependencies:
  image_picker: ^0.6.3+4
  location: ^2.5.0
  true_time: ^0.1.0
  rflutter_alert: ^1.0.3
  dio: ^3.0.9
  http: ^0.12.0+4
  fluro: "^1.1.0"
  flutter_launcher_icons: ^0.7.4
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  intl: "^0.15.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/antivirus.png"
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/coronavirus.jpg
    - assets/corona.jpg
    - assets/antivirus.png
    - assets/no.png
    - assets/restaurant.jpg
    - assets/cafe.jpg
    - assets/rassemblement.jpg
    - assets/docteur.jpg
    - assets/restau.jpg
    - assets/auto.jpg
    - assets/couvreFeu.jpg
    - assets/quarantaine.jpg
    - assets/team.png
    - assets/caffe.png
    - assets/restauu.png
    - assets/stayhome.png
    - assets/quarantine.jpg
    - assets/staysafe.png
    - assets/confinement.png
    - assets/ministere.png
    - assets/obs.png
    - assets/logo.png
    - assets/junior.png
    - assets/junior2.png
    - assets/a.png
    - assets/logoM.png
    - assets/cash.png
    - assets/vente.jpg
    - assets/france.jpg
    - assets/tunisie.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bangers
      fonts:
        - asset: fonts/Bangers-Regular.ttf
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: ZhiMangXing
      fonts:
        - asset: fonts/ZhiMangXing-Regular.ttf
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: AyeshaBurns
      fonts:
        - asset: fonts/AyeshaBurnsDemoRegular.ttf   
    - family: Gnaw
      fonts:
        - asset: fonts/Gnaw FREE.ttf   
    - family: SOPHIA
      fonts:
        - asset: fonts/SOPHIA demo.ttf  
    - family: Starlight
      fonts:
        - asset: fonts/Starlight demo.ttf  
    - family: Walahard
      fonts:
        - asset: fonts/Walahard Regular.ttf          
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
